### ISSUE TITLE
quick crash due to make errors for default run.

### ISSUE THREAD

**Issue by bishopia** [bcgsc/LongStitch#26]
Hi all,
I'm having trouble getting things going with LongStitch, not sure why the following error is cropping up. I've got a fresh conda env running and I think I have the input files right (correct file types and in working dir). Any help much appreciated.

command
```
source activate /gpfs/home/ibishop/data/ibishop/condas/longstitch
longstitch run draft=mfa1red2merge1 reads=ccs G=2.1e9 t=10
```

working dir
```
(miniconda3)[ibishop@login006 longstitch]$ lr
total 16G
-rw-r--r-- 1 ibishop 2.1G Dec  1 08:37 mfa1red2merge1.fa
-rw-r--r-- 1 ibishop  13G Dec  1 08:59 ccs.fastq.gz
drwxr-sr-x 4 ibishop 4.0K Dec  1 09:44 longstitch-1.0.1
-rw-r--r-- 1 ibishop 2.6K Dec  1 09:46 slurm-3464760.out
-rw-r--r-- 1 ibishop  289 Dec  1 09:50 longstitch.sh
-rw-r--r-- 1 ibishop 2.6K Dec  1 09:50 slurm-3464768.out
```

error
```
###############################################################################
tigmint-make tigmint-long draft=mfa1red2merge1 reads=ccs cut=250 t=10 G=2.1e9 span=auto dist=auto
make[1]: Entering directory '/gpfs/scratch/ibishop/longstitch'
sh -c 'gunzip -c  | \
/gpfs/home/ibishop/data/ibishop/condas/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_estimate_dist.py - -n 1000000 -o ccs.tigmint-long.params.tsv'

gzip: stdin: unexpected end of file
Traceback (most recent call last):
  File "/gpfs/home/ibishop/data/ibishop/condas/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_estimate_dist.py", line 63, in <module>
    main()
  File "/gpfs/home/ibishop/data/ibishop/condas/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint_estimate_dist.py", line 55, in main
    dist = int(np.percentile(read_lengths, args.p))
  File "<__array_function__ internals>", line 5, in percentile
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3732, in percentile
    return _quantile_unchecked(
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3851, in _quantile_unchecked
    r, k = _ureduce(a, func=_quantile_ureduce_func, q=q, axis=axis, out=out,
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3429, in _ureduce
    r = func(a, **kwargs)
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/lib/function_base.py", line 3967, in _quantile_ureduce_func
    x1 = take(ap, indices_below, axis=axis) * weights_below
  File "<__array_function__ internals>", line 5, in take
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 191, in take
    return _wrapfunc(a, 'take', indices, axis=axis, out=out, mode=mode)
  File "/users/ibishop/.local/lib/python3.9/site-packages/numpy/core/fromnumeric.py", line 58, in _wrapfunc
    return bound(*args, **kwds)
IndexError: cannot do a non-empty take from an empty axes.
make[1]: *** [/gpfs/home/ibishop/data/ibishop/condas/longstitch/bin/share/tigmint-1.2.5-0/bin/tigmint-make:248: ccs.tigmint-long.params.tsv] Error 1
make[1]: Leaving directory '/gpfs/scratch/ibishop/longstitch'
make: *** [/gpfs/home/ibishop/data/ibishop/condas/longstitch/bin/share/longstitch-1.0.1-1/longstitch:155: mfa1red2merge1.cut250.tigmint.fa] Error 2
```

**Comment by bishopia** [comment]
fq.gz required, not fastq.gz. sorry!

**Comment by lcoombe** [comment]
Glad you got it working with adjusting the file suffix!
