### ISSUE TITLE
Problems with tigment when trying to run LongStitch

### ISSUE THREAD

**Issue by Lean-s** [bcgsc/LongStitch#44]
Hi, 

We've run into some problems when trying to install LongStitch via Conda, we first tried a fresh install via the standard method mentioned in the readme but we came across the following error when running './run_longstitch_demo.sh'.
```
+ echo 'Launching LongStitch test runs...'
Launching LongStitch test runs...
+ echo 'Ensure all dependencies are in your PATH'
Ensure all dependencies are in your PATH
+ echo 'Running first test - default LongStitch steps...'
Running first test - default LongStitch steps...
+ longstitch -B run draft=test_scaffolds1 reads=test_reads1 G=482700 k_ntLink=24
tigmint-make tigmint-long draft=test_scaffolds1 reads=test_reads1 cut=250 t=8 G=482700 span=auto dist=auto
make[1]: Entering directory '/mnt/NAS/bin3e/longstitch/longstitch-1.0.2/tests'
PYTHONPATH=/opt/anaconda3/envs/longstitch_test/bin/share/tigmint-1.2.6-0/bin/../src/btllib/install/python/  /opt/anaconda3/envs/longstitch_test/bin/share/tigmint-1.2.6-0/bin/tigmint_estimate_dist.py test_reads1.fa.gz -n 1000000 -o test_reads1.tigmint-long.params.tsv
Traceback (most recent call last):
  File "/opt/anaconda3/envs/longstitch_test/bin/share/tigmint-1.2.6-0/bin/tigmint_estimate_dist.py", line 10, in <module>
    import btllib
ModuleNotFoundError: No module named 'btllib'
make[1]: *** [/opt/anaconda3/envs/longstitch_test/bin/share/tigmint-1.2.6-0/bin/tigmint-make:270: test_reads1.tigmint-long.params.tsv] Error 1
make[1]: Leaving directory '/mnt/NAS/bin3e/longstitch/longstitch-1.0.2/tests'
make: *** [/opt/anaconda3/envs/longstitch_test/bin/share/longstitch-1.0.2-0/longstitch:179: test_scaffolds1.cut250.tigmint.fa] Error 2
```
We fixed this by downgrading the tigmint packages to version 1.2.5 but then we came across the following error:
```
+ echo 'Launching LongStitch test runs...'
Launching LongStitch test runs...
+ echo 'Ensure all dependencies are in your PATH'
Ensure all dependencies are in your PATH
+ echo 'Running first test - default LongStitch steps...'
Running first test - default LongStitch steps...
+ longstitch -B run draft=test_scaffolds1 reads=test_reads1 G=482700 k_ntLink=24
tigmint-make tigmint-long draft=test_scaffolds1 reads=test_reads1 cut=250 t=8 G=482700 span=auto dist=auto
make[1]: Entering directory '/mnt/NAS/bin3e/longstitch/longstitch-1.0.2/tests'
sh -c 'gunzip -c test_reads1.fa.gz | \
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_estimate_dist.py - -n 1000000 -o test_reads1.tigmint-long.params.tsv'
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g482700 -s -b test_reads1.barcode-multiplicity.tsv --bx -t8 --fasta -f test_reads1.tigmint-long.params.tsv test_reads1.fa.gz | \
minimap2 -y -t8 -x map-ont --secondary=no test_scaffolds1.fa - | \
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py -q0 -s2000 -p test_reads1.tigmint-long.params.tsv - | sort -k1,1 -k2,2n -k3,3n > test_scaffolds1.test_reads1.cut250.molecule.size2000.distauto.bed
long-to-linked-pe v1.2.5: Using more than 6 threads does not scale, reverting to 6.
[M::mm_idx_gen::0.039*0.53] collected minimizers
[M::mm_idx_gen::0.050*1.14] sorted minimizers
[M::main::0.050*1.14] loaded/built the index for 17 target sequence(s)
[M::mm_mapopt_update::0.052*1.13] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 17
[M::mm_idx_stat::0.054*1.13] distinct minimizers: 89265 (98.86% are singletons); average occurrences: 1.016; average spacing: 5.325; total length: 482826
Traceback (most recent call last):
  File "/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 141, in <module>
    main()
  File "/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 138, in main
    MolecIdentifierPaf().run()
  File "/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 91, in run
    self.print_new_molecule(prev_barcode, cur_intervals, out_molecules_file)
  File "/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 44, in print_new_molecule
    assert barcode_match
AssertionError
make[1]: * [/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/tigmint-make:260: test_scaffolds1.test_reads1.cut250.molecule.size2000.distauto.bed] Error 1
make[1]: * Deleting file 'test_scaffolds1.test_reads1.cut250.molecule.size2000.distauto.bed'
make[1]: Leaving directory '/mnt/NAS/bin3e/longstitch/longstitch-1.0.2/tests'
make: * [/home/nas_minion/.conda/envs/longstitch_env/bin/share/longstitch-1.0.1-2/longstitch:155: test_scaffolds1.cut250.tigmint.fa] Error 2
```
Any suggestions to fix this problem?

Thanks!

**Comment by lcoombe** [comment]
Hi @Lean-s,

First, thanks for flagging the issue with Tigmint v1.2.6 in conda - I'll take a look at why that error is happening and get back to you. The error that's happening is due to a new dependency that should be properly handled in the installation.

For the v1.2.5 error - it appears that there's an issue with simulating the linked reads. Could you please do this test for me to troubleshoot - Just run: 
```
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g482700 -s -b test_reads1.barcode-multiplicity.tsv --bx -t8 --fasta -f test_reads1.tigmint-long.params.tsv test_reads1.fa.gz 
```
and report back some of the lines of the output? With that, we're looking to see 250bp reads in a fasta file, with a barcode in the header in the format `BX:Z:<barcode>`.

In addition, could you let us know what machine/OS you are running LongStitch on?

Thanks for your interest in LongStitch!
Lauren

**Comment by Lean-s** [comment]
Hi @lcoombe,

Thanks for your fast respond and looking into it. 
The command gave the following output (first 3 reads): 
```
long-to-linked-pe v1.2.5: Using more than 6 threads does not scale, reverting to 6. 
>6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f1 BX:Z:1 
CTGTACTTTGGATTCAGTTACGTATTGCTTTAAGCCTAACAGCTCAACACACACAAATGGATGACCGTTAAATATGATGATTGTTATCAATCCCAGCATTGTTGAGTAAGCTGCCACGGTCAGCCTCAGAATCAACTCCTGGAACCATTGCTCCTGTTTATTGGGAGACAATGATGATTTCATCAGACCATGGGAATGGCTGAAATTGAATATTTAGTAGGAATGCATTTTTCAAGAATGGATTAGTTCC 
>6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f1 BX:Z:1 
ATAACATGTTCTGAGCTGTAGCTGCTTGAATACAGTTTCATTGAATCATTATTTTGGTCTATCATCAAGACTAAAATTCACCTGCAAATCAGATTGAATAAACGTAAAATTAACAACCAAAACATGAAAAAAGTGACATAATAAAATAACACTATCTGACGTTTGCAAATAATAAGAAAAGACAAATTATGATTTTAGCAAAACTTCATTTTTTGCAATTTAGAATCACACATTTTTTTTCTTGAAAACT 
>6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f2 BX:Z:1 
TTCATTGGAGTTGGCTAAGACACCCTAACTACTCTTTTTTTGAAATTTTTTTAACCATCTTGAGGAATTTATTGAGGATAAATCGTTTTTTTAATTACTTTGAAACATAAATTATAAAATTGTATAATCATTTTAAAAGCTTGATTGTAGAAATTAAATTCAAAAAAAGCGATATTTTTTTTTTTAATTTCGTTTTGAATATTATTAAAACTTCACAGTCATCCTTTTTTAGTTGAAATACTGGAAAGAT 
```
We're running LongStitch on a Linux system (Ubuntu 20.04.4 LTS) with 8 threads and 65GB of ram.

**Comment by lcoombe** [comment]
Thanks @Lean-s,

Ok so that output looks to be formatted as expected, so the `long-to-linked-pe` step appears to be working OK. 
Could you do another small test for me? 

```
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g482700 -s -b test_reads1.barcode-multiplicity.tsv --bx -t8 --fasta -f test_reads1.tigmint-long.params.tsv test_reads1.fa.gz | \
minimap2 -y -t8 -x map-ont --secondary=no test_scaffolds1.fa -
```
And also post some of the first lines? I'm just trying to work through that command step-by-step to get more clues about where things are going wrong!

**Comment by Lean-s** [comment]
Of course, it gave the following results.
```
(longstitch_env) nas_minion@administrator-Standard-PC-i440FX-PIIX-1996:~/longstitch_test_issue$ /home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g482700 -s -b test_/nas_minion/bin3e/longstitch/longstitch-1.0.2/tests/reads1.barcode-multiplicity.tsv --bx -t8 --fasta -f /nas_minion/bin3e/longstitch/longstitch-1.0.2/tests/test_reads1.tigmint-long.params.tsv /nas_minion/bin3e/longstitch/longstitch-1.0.2/tests/test_reads1.fa.gz | minimap2 -y -t8 -x map-ont --secondary=no /nas_minion/bin3e/longstitch/longstitch-1.0.2/tests/test_scaffolds1.fa -
long-to-linked-pe v1.2.5: Using more than 6 threads does not scale, reverting to 6.
[M::mm_idx_gen::0.027*0.80] collected minimizers
[M::mm_idx_gen::0.039*1.52] sorted minimizers
[M::main::0.039*1.52] loaded/built the index for 17 target sequence(s)
[M::mm_mapopt_update::0.041*1.49] mid_occ = 10
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 17
[M::mm_idx_stat::0.042*1.48] distinct minimizers: 89265 (98.86% are singletons); average occurrences: 1.016; average spacing: 5.325; total length: 482826
6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f1    250     47      215     +       187190  22186   1865    2035    59      171     25      tp:A:P  cm:i:5  s1:i:58 s2:i:0    dv:f:0.0222     rl:i:0  BX:Z:1
6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f1    250     105     248     -       187190  22186   2068    2223    54      155     16      tp:A:P  cm:i:5  s1:i:51 s2:i:0    dv:f:0.0222     rl:i:0  BX:Z:1
6ff0912c-0558-44d3-9df5-316da8bc76db_Basecall_1D_template_f2    250     32      155     +       187190  22186   2352    2473    51      123     16      tp:A:P  cm:i:5  s1:i:51 s2:i:0    dv:f:0.0308     rl:i:0  BX:Z:1
[M::worker_pipeline::1.341*1.12] mapped 68154 sequences
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -y -t8 -x map-ont --secondary=no /nas_minion/bin3e/longstitch/longstitch-1.0.2/tests/test_scaffolds1.fa -
[M::main] Real time: 1.348 sec; CPU: 1.504 sec; Peak RSS: 0.042 GB
```

**Comment by lcoombe** [comment]
Thanks @Lean-s  - Again, it's curious because that output sample looks OK with the `BX:Z` tag... 

Could we try a couple of things:
1. I updated the conda recipe which should fix the error with v1.2.6 you were seeing (https://github.com/bioconda/bioconda-recipes/pull/34292). Could you update Tigmint to that version and try again? It's possible that this is due to an issue in the `btllib` dependency that was updated in the most recent version
2. If you still see the error, could you run:
```
/home/nas_minion/.conda/envs/longstitch_env/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g482700 -s -b test_reads1.barcode-multiplicity.tsv --bx -t8 --fasta -f test_reads1.tigmint-long.params.tsv test_reads1.fa.gz | \
minimap2 -y -t8 -x map-ont --secondary=no test_scaffolds1.fa - > demo_mappings.paf
```
And then send the output file `demo_mappings.paf` to me? You could either attach it here, add it to a github gist or e-mail me at lcoombe@bcgsc.ca. Then I can have a full look through the file to see if I can help decode what's going on

**Comment by Lean-s** [comment]
Hi @lcoombe, 

Thanks for your time for looking into it, the update fixed the issue from tigmint. We discovered that our system had issues with symlinks, that caused Error 1 and 2 but now everything works as expected.

**Comment by lcoombe** [comment]
@Lean-s - Great, glad to hear the update solved the issue!
