### ISSUE TITLE
Longstitch "std::invalid_argument"

### ISSUE THREAD

**Issue by MBinso** [bcgsc/LongStitch#60]
Hi,

I have recently tried to use LongStitch with PacBio longreads and a draft genome of around 6.8Mb.  I have the 1.0.3 version installed through conda. Sadly I have been getting the following error:

`$ longstitch run draft=she_draft reads=reads G= 48e5`

```
tigmint-make tigmint-long draft=she_draft reads=reads cut=250 t=8 G= span=auto dist=auto
make[1]: Entering directory '/home/guillermo/Assemblies/PacBio_Shewanella/Trial_assembly_v6/Scaffolds_longstich'
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/../src/long-to-linked-pe -l 250 -m2000 -g -s -b reads.barcode-multiplicity.tsv --bx -t8 --fasta -f reads.tigmint-long.params.tsv reads.fq.gz | \
minimap2 -y -t8 -x map-ont --secondary=no she_draft.fa - | \
/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py -q0 -s2000 -p reads.tigmint-long.params.tsv - | sort -k1,1 -k2,2n -k3,3n > she_draft.reads.cut250.molecule.size2000.distauto.bed
zsh: /home/guillermo/miniconda3/bin/../lib/libtinfow.so.6: no version information available (required by zsh)
terminate called after throwing an instance of 'std::invalid_argument'
  what():  stod
[M::mm_idx_gen::0.168*0.93] collected minimizers
[M::mm_idx_gen::0.235*1.15] sorted minimizers
[M::main::0.235*1.15] loaded/built the index for 62 target sequence(s)
[M::mm_mapopt_update::0.249*1.14] mid_occ = 13
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 62
[M::mm_idx_stat::0.260*1.14] distinct minimizers: 864154 (98.42% are singletons); average occurrences: 1.033; average spacing: 5.345; total length: 4770263
[M::main] Version: 2.24-r1122
[M::main] CMD: minimap2 -y -t8 -x map-ont --secondary=no she_draft.fa -
[M::main] Real time: 0.268 sec; CPU: 0.304 sec; Peak RSS: 0.047 GB
Traceback (most recent call last):
  File "/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 141, in <module>
    main()
  File "/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 138, in main
    MolecIdentifierPaf().run()
  File "/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 98, in run
    self.print_new_molecule(prev_barcode, cur_intervals, out_molecules_file)
  File "/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint_molecule_paf.py", line 43, in print_new_molecule
    barcode_match = re.search(r'^BX:Z:(\S+)', barcode)
  File "/home/guillermo/miniconda3/lib/python3.7/re.py", line 185, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object
make[1]: *** [/home/guillermo/miniconda3/bin/share/tigmint-1.2.5-1/bin/tigmint-make:260: she_draft.reads.cut250.molecule.size2000.distauto.bed] Error 1
make[1]: *** Deleting file 'she_draft.reads.cut250.molecule.size2000.distauto.bed'
make[1]: Leaving directory '/home/guillermo/Assemblies/PacBio_Shewanella/Trial_assembly_v6/Scaffolds_longstich'
make: *** [/home/guillermo/miniconda3/bin/share/longstitch-1.0.3-0/longstitch:183: she_draft.cut250.tigmint.fa] Error 2
```

I have also used awk to set the draft genome as a one line fasta for each contig but the error remains.  I have set soft links for my reads file which is in fastq.gz format and for the draft genome which is also in fasta format. I am unsure on why is this happening. I hope you can give me some advice on this.

 Thank you for your time.

**Comment by lcoombe** [comment]
Hello @MBinso,

In your command, looks like you have an extra space between `G=` and your specified genome size? There shouldn't be any spaces when specifying those parameters. Try removing that so that the value is properly passed into the program and see if you get any further.

If you're still having issues, a few questions:
- Did you install longstitch in a fresh conda environment? Or an existing environment? 
- Did you try running our test demo, and did that run properly or did you see a similar error?

Thank you for your interest in LongStitch!
Lauren

**Comment by MBinso** [comment]
It appears that the space was causing the error. Thank you very much !!

**Comment by lcoombe** [comment]
Great, I'm glad that solved the issue for you!
